Args = --initialize-at-run-time=org.apache.poi.ss.formula.udf.IndexedUDFFinder \
       --initialize-at-run-time=org.apache.poi.ss.formula.udf.AggregatingUDFFinder \
       --initialize-at-run-time=org.apache.poi.ss.formula.function.FunctionMetadataRegistry \
       --initialize-at-run-time=org.apache.poi.ss.formula.function.FunctionMetadataReader