# 基础公用的配置参数放置在这份yml中
# 项目相关配置
fortuneboot:
  # 名称
  name: 好记
  # 版本
  version: 1.2.0
  # 版权年份
  copyright-year: 2025
  # 实例演示开关
  demo-enabled: true
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 对应的公钥放在前端项目中的utils/rsaUtils类中
  rsaPrivateKey: ${RSA_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6OQ7qmZide2sI4mK1ASnOIexsGAvAHeLFsRC5NdKjt0xf3L6NvMNC39/eJGpT/YYMBnV0WkL1gzJXdN3iR1iXBo5wm7W3IULsB8S5oMmZ+uXDOzzKQMLVCXImK7a6fIjCVKJ1rd1yMdYIBSg38q5tIvq9Etj/Rqa4LOXhbKztudyp4IEQkKWwQ81NfnuCWFjWcgZ6L7VKdwoweDEi5142c/nBXXOoAQ18ZYxuxUZobdhDh3ej/2eHaTmTRi3BZngc9+3LUGGi8JnfJVbRVwzqV7/2Uc+OO454QNeyAYysE/gLMUfhUDAO05g8+12whWxzdAg/kGx8DTb12RQU8mMhAgMBAAECggEACrG0bk1i7UclSkbkxtCJ2+px87vBxrTC8dVo2uDcibPA6A/WM0r5FDjJoRt4QEdivkydzCKcjhGxI/l0R2sPeOllDGR0xJg40zMp3WjZ+LJ5JV7lXPLn/WjRmg2QUT0EvPeh2wvpvGE7/zGgDTebjP980nKMf1a3MbsFw2mW/Uhmm+ij4Hcpzi0h8/K6J0GdXTMIWRXdW2VjyPaIGtOje3tKwzUuu2AVFY2FF1IpfoRydAQZppLogeofeAGxGJzNagqZhV1lpYQQwTnFZzRuBHsIHAW4VAWeuSXqLgf3+/MhnDYuVJFqjnYXRe529SJarN5yo5vXoXfSFJedr+tDLQKBgQD2jc4XaTkygUwfSNyaZiNS7kBLEUcnryBPkIxhPfsO0a6Cd6nB2HeQgPfkgm24+614TPpZqGN0tBWGVR5F4kToFycEFPjegEBGRSaHXtktE3ZrfjuQxjnlgpyHJoSmHslJL3evIOpnTUpHG+ybVJ0oKAjlcFiV7NBwnlsP8Yi9SwKBgQDBW4cfDqIC2UuH0HGJ/JzgmIjjLKC2fSKuVmsD+TrmwCDl52CO5c1XZr43aKCb+8r395UeHKYHi4DFjQn9OpE4pX0GXGyggcCflH+eKcUMLOdBlbntY1R3zmO2M0jLvOrrsaJuz0g8Q1zoajeKSfA6eYmpfHZ1gJeN9qvQVp25wwKBgQCBi+Lk1Cn0ipF3wq3/Bnm7AmqPxuVPSao9hCLumUWH9M6vyLZOnzG7oLgfvhRu5Paxxiio4VxYnqLMsX61k31HQZsDfw2Aw3yCL6Vd7Y1JLPfE5U/g8vbKzAT40llSe8yhgqptP2tKmgbUNCzvNNdamSaLf6tcI1EmS15nky6Y3wKBgCzv15xZKz/cPliHEgwOoGr2KEIbuhIPTQMVZHOc9ZpxJnQn7OHo+GsKnsSD1WfLAeXVLVu9LrzsJ/ZBjAPFG8D9fOwAiOJYpWqw+WPJs1jcCrbMVFSeVCAv4C6VBqMK+dHjC6wTEmenBC2jmdrSyjjczCiOm309cHt2y4F0z90/AoGANyxVCvn5ZOIgkLF+eK6fngnu0kYZf2nxRyX5T0vdXFQLP0wDfDQOz/RNaMVeHCpJ7KnWGFT2xwd0WiUP9+cmVDUrmSfw89scf4JLdpkyvrKb2K/Rl7ekLbfgRbNWuyd2Ht1A/KQU3Ll7zSY/8WnT0eqKiBWftMmsWfylVx1IKkw=}
  rsaPublicKey: ${RSA_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAujkO6pmYnXtrCOJitQEpziHsbBgLwB3ixbEQuTXSo7dMX9y+jbzDQt/f3iRqU/2GDAZ1dFpC9YMyV3Td4kdYlwaOcJu1tyFC7AfEuaDJmfrlwzs8ykDC1QlyJiu2unyIwlSida3dcjHWCAUoN/KubSL6vRLY/0amuCzl4Wys7bncqeCBEJClsEPNTX57glhY1nIGei+1SncKMHgxIudeNnP5wV1zqAENfGWMbsVGaG3YQ4d3o/9nh2k5k0YtwWZ4HPfty1BhovCZ3yVW0VcM6le/9lHPjjuOeEDXsgGMrBP4CzFH4VAwDtOYPPtdsIVsc3QIP5BsfA029dkUFPJjIQIDAQAB}
  # 是否检查 i18n 资源文件（messages.properties）是否都有对应的键值对
  checkI18nKey: false
  traceRequestIdKey: AG-RequestId



## 开发环境配置
#server:
#  # 服务器的HTTP端口，默认为8080
#  port: 8080
#  servlet:
#    # 应用的访问路径
#    context-path: /
#  tomcat:
#    # tomcat的URI编码
#    uri-encoding: UTF-8
#    # 连接数满后的排队数，默认为100
#    accept-count: 1000
#    threads:
#      # tomcat最大线程数，默认为200
#      max: 800
#      # Tomcat启动初始化的线程数，默认值10
#      min-spare: 100

# 日志配置
logging:
  level:
    # 记得配置到包名
    com.fortuneboot: debug
    org.springframework: info
  pattern:
    console: "%date requestId:%X{${fortuneboot.traceRequestIdKey}} %thread %green(%level) [%cyan(%logger{10}):%magenta(%line)] %red(%method) | %msg%n"


# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    # 有些版本的 IDEA  会自动设置properties的编码为IOS-8859-1 请在IDEA配置里设置成UTF8
    encoding: UTF-8

  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  5MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关  线上记得关闭
      enabled: false
  # compatible with swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss



# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥 TODO 记得更换
    secret: Noyvfhx7MzInoYP5PAyrBqz6ZdGUpLb/qV3cIaM3H5JcDIi7L1ddLVhLVowGezO24ztckyj0duWWUrw7onDuhA==
    # 自动刷新token的时间
    autoRefreshTime: 20

# MyBatis配置
mybatis-plus:
    # 搜索指定包别名 使用简短的类型名称来代替完整的类型名称
#    typeAliasesPackage: com.fortuneboot.orm.*
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configuration:
      cacheEnabled: true
      useGeneratedKeys: true
      defaultExecutorType: SIMPLE
      logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    global-config:
      refresh: true


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: com.fortuneboot





