
# 测试环境配置（使用 SQLite）
db:
    type: sqlite

spring:
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:data/fortuneboot-test.db

logging:
    file:
        path: logs/fortuneboot-test

springdoc:
    swagger-ui:
        enabled: false

# 项目相关配置
fortuneboot:
    file-base-dir: data/fortuneboot-test
    api-prefix: /test-api
    demo-enabled: false