# 开发环境数据源配置（仅在 db.type=mysql 时生效）
spring:
    datasource:
        druid:
            url: jdbc:mysql://${DB_HOST:mysql.fortuneboot.com}:${DB_PORT:30306}/${DB_NAME:fortune_boot}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useSSL=true&serverTimezone=GMT%2B8
            username: ${DB_USERNAME:root}
            password: ${DB_PASSWORD:Jk9Lm2XqPvZt8N7e}
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            # Druid 监控控制台
            statViewServlet:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: fortuneboot
                login-password: 123456
            # Druid 过滤器
            filter:
                stat:
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

logging:
    file:
        path: logs/fortuneboot-dev


springdoc:
    swagger-ui:
        # ***注意*** 开启Swagger UI界面  **安全考虑的话生产环境需要关掉**
        # 因为knife4j的一些配置不灵活 所以重新改回springdoc+swagger的组合  真实开发的时候 使用apifox这种工具效率更高
        enabled: true
        url: ${fortuneboot.api-prefix}/v3/api-docs
        config-url: ${fortuneboot.api-prefix}/v3/api-docs/swagger-config


# 项目相关配置
fortuneboot:
    # 文件基路径 示例（ Windows配置D:\fortuneboot，Linux配置 /home/fortuneboot）
    file-base-dir: D:\fortuneboot
    # 前端url请求转发前缀
    api-prefix: /dev-api
    demo-enabled: false